version: "3.8"
services:
    # imagem 
    app:
        container_name: app
        image: app
        build: 
            args: 
                user: elessandro
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
            - queue
        networks: 
            - api
    
    # nginx 
    nginx:
        container_name: nginx
        image: nginx:alpine
        restart: unless-stopped
        ports: 
            - 8000:80
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - api

    # postgres 
    db:
        container_name: db-postgres
        image: postgres:14.0-alpine
        restart: unless-stopped
        environment: 
            POSTGRES_DB: laravel
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        volumes: 
            - ./.docker/postgres_data:/var/lib/postgresql/data
        ports: 
            - 5432:5432
        networks: 
            - api

    # sgbd 
    adminer:
        container_name: adminer
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
        depends_on: 
            - db
        networks: 
            - api

    # queue 
    queue:
        container_name: queue
        image: queue
        build: 
            args: 
                user: elessandro
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - api

    #redis
    redis:
        container_name: redis
        image: redis:latest
        networks: 
            - api

networks: 
    api:
        driver: bridge